steps:
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "-r", "dataflow", "gs://mounika-healthcare-data/"]

  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "-r", "config", "gs://mounika-healthcare-data/"]

  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "setup.py", "gs://mounika-healthcare-data/"]

  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "requirements.txt", "gs://mounika-healthcare-data/"]

  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "-r", "airflow/dags", "gs://mounika-healthcare-data/airflow/"]

  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "-r", "sql", "gs://mounika-healthcare-data/"]

options:
  logging: CLOUD_LOGGING_ONLY