steps:
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      - "cp"
      - "-r"
      - "dataflow"
      - "gs://mounika-healthcare-data/"

  - name: "gcr.io/cloud-builders/gsutil"
    args:
      - "cp"
      - "-r"
      - "config"
      - "gs://mounika-healthcare-data/"

  - name: "gcr.io/cloud-builders/gsutil"
    args:
      - "cp"
      - "-r"
      - "airflow/dags/*"
      - "gs://mounika-healthcare-data/airflow/dags/"

options:
  logging: CLOUD_LOGGING_ONLY
